### ISSUE TITLE
Amazing project

### ISSUE THREAD

**Issue by pawamoy** [nickderobertis/terminhtml#11]
Wow, this is a really nice project!

I've used and tried many command line SVG recorder/renderers, and this one is definitely the *easiest* to use, by far.
It deserves many more views and stars :star: !

I'll probably open a few issues next :smile:

**Comment by nickderobertis-cov** [comment]
So glad to hear it! I was also unhappy with the current set of tools and wanted something with selectable text and that is more interactive. It's still early-stage so open to all feedback!

**Comment by nickderobertis** [comment]
Glad to hear it! I was also unhappy with the current set of tools and wanted something with selectable text and that is more interactive. This is still early-stage so open to all feedback!
